# Welcome to Jekyll!
#

# Site settings
title: Brighter3D rendering plugin for SketchUp
description: |
  Easily create photorealistic renders<br />
  from your SketchUp scenes<br />
  with Brighter3D!  
owner: Brighter3D Software Development Ltd.
first_published: 2018 # if migrating another site, the year of your first publish
email: support@brighter3d.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.brighter3d.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/Brighter3D
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/Brighter3D
  google-plus-square: https://plus.google.com/u/0/+LukaszPiwowarBrighter3D/posts
  #https://plus.google.com/+LukaszPiwowarBrighter3D/posts
  email: mailto:support@brighter3d.com
  #flickr:
  #instagram:
  youtube-square: https://www.youtube.com/channel/UCczbXVkENusX3wZKgpzID4Q
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
