# Welcome to Jekyll!
#

# Site settings
title: Brighter3D rendering plugin for SketchUp
description: |
  Easily create photorealistic renders<br />
  from your SketchUp scenes<br />
  with Brighter3D!<br /><br />
  Now version 3.1.1 <br />
  ready for SketchUp 2019.2 <br />
  released

owner: Brighter3D Software Development Ltd.
first_published: 2013-2019 # if migrating another site, the year of your first publish
email: support@brighter3d.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.brighter3d.com/" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/Brighter3D
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/Brighter3D
  #google-plus-square: 
  #email:
  flickr: https://www.flickr.com/photos/183812616@N07/
  instagram: https://www.instagram.com/brighter3d
  youtube-square: https://www.youtube.com/channel/UCczbXVkENusX3wZKgpzID4Q
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  tumblr-square: https://brighter3d.tumblr.com/
  pinterest-square: https://www.pinterest.com/brighter3d/
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
